### PR TITLE
Fix Repository

### PR DESCRIPTION
**Pull request by Jason54jg**

### CODE REVIEW

**Comment by Exortions** [comment]
Why is this necessary?

**Comment by UltraBlackLinux** [comment]
why did you add this? What are the benefits? Why is this an unofficial mirror? Is this a backdoored version?

**Comment by Jason54jg** [comment]
I replaced the repository because the old one can no longer download (spigot-parent) and it made an error in the compilation unless it's just for me

**Comment by Exortions** [comment]
Seems like that's just for you, I've never had that issue using the current repository.

**Pull request closed without merging**
